import type { Metadata } from "next"
import { Instrument_Serif, DM_Sans } from "next/font/google"
import "./globals.css"

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
})

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${instrumentSerif.variable} ${DMSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
